---
- hosts: all
  name: Minimal development tools
  vars:
    dev_minimal:
      # Editors
      - vim

      # Version Control
      - git

      # Interpreters, compilers, runtimes, etc...
      - gcc

      - python3
      - python3-pip
      - python3-venv

      - npm

      # Build tools
      - make
      - cmake

      # Debugging
      - gdb

      # Containerization
      - docker.io

  tasks:
    - name: Install packages
      become: yes
      apt:
        name: "{{ dev_minimal }}"
        state: present
