---
- hosts: all
  name: General utilities
  vars:
    general:
      - curl
      - wget
      - unzip
      - zip
      - jq
      - tree
      - htop
      - net-tools
      - iputils-ping
      - dnsutils

      - fonts-noto

  tasks:
    - name: Install packages
      become: yes
      apt:
        name: "{{ general }}"
        state: present
