---
- hosts: all
  name: Hardware drivers
  become: yes
  vars:
    nvidia_driver_version: "470"
  tasks:
    - name: Add graphics-drivers PPA
      apt_repository:
        repo: ppa:graphics-drivers/ppa
        state: present

    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install NVIDIA drivers
      apt:
        name: "nvidia-driver-{{ nvidia_driver_version }}"
        state: present
