---
- hosts: all
  name: Install entire system.
  tasks:
    - name: Update apt cache
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600

- import_playbook: general.yml
- import_playbook: dev_minimal.yml
- import_playbook: desktop.yml
- import_playbook: playbooks/nvim.yml
- import_playbook: playbooks/oscp.yml
