---
- hosts: all
  name: Install dotfiles
  vars:
    dotfiles_dir: "{{ ansible_facts['env']['HOME'] }}/dotfiles"
  tasks:
    - name: Clone or update dotfiles repository
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dir }}"
        update: true
        force: true
      register: git_clone

    - name: Ensure GNU Stow installed
      become: true
      apt:
        name: stow
        state: present

    - name: Stow dotfiles
      shell: |
        cd {{ dotfiles_dir }}
        stow --no-folding .
      when: git_clone is defined and git_clone.changed
