---
- hosts: all
  name: Install dotfiles
  vars:
    dotfiles_dir: "{{ ansible_env.HOME }}/dotfiles"
  tasks:
    - name: Check if dotfiles repo already cloned
      stat:
        path: "{{ dotfiles_dir }}"
      register: dotfiles_dir_stat

    - name: Clone dotfiles repository
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dir }}"
        update: no
      when: not dotfiles_dir_stat.stat.exists
      register: git_clone

    - name: Ensure GNU Stow installed
      become: yes
      apt:
        name: stow
        state: present

    - name: Stow dotfiles
      shell: |
        cd {{ dotfiles_dir }}
        stow --no-folding .
      when: git_clone is defined and git_clone.changed
