---
- hosts: localhost
  vars:
    venv_dir: "{{ ansible_facts['env']['HOME'] }}/.local/venvs/i3_scripts"
  tasks:
    - name: Ensure python3-venv is installed
      apt:
        name: python3-venv
        state: present
      become: true

    - name: Create virtual environment
      command:
        cmd: python3 -m venv {{ venv_dir }}
        creates: "{{ venv_dir }}"

    - name: Install i3ipc into venv
      pip:
        name: i3ipc
        virtualenv: "{{ venv_dir }}"
        state: present

    - name: Ensure ~/.config/i3 directory exists
      file:
        path: "{{ ansible_facts['env']['HOME'] }}/.config/i3"
        state: directory

    - name: Ensure i3 scripts are executable
      file:
        path: "{{ ansible_facts['env']['HOME'] }}/.config/i3/scripts"
        mode: u+x
        state: directory
        recurse: true
